UNRCE-django/UNRCE/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
  path('captcha/', include('captcha.urls')),
  path("", include("UNRCE_APP.urls")),

  # Default django admin interface
  path("admin/", admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

UNRCE-django/UNRCE_APP/urls.py
from django.urls import path, reverse_lazy, re_path
from .views import IndexView, SignUpView, CreateProject,CustomLoginView #, UploadImageView
from django.contrib.auth.views import LogoutView
from . import views
from .forms import CustomAuthenticationForm

app_name = "UNRCE_APP"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path(
        "login/",
        CustomLoginView.as_view(
            authentication_form=CustomAuthenticationForm,
            template_name="UNRCE_APP/login.html",
            success_url=reverse_lazy("UNRCE_APP:index"),
            redirect_authenticated_user=True,
        ),
        name="login",
    ),
    path(
        "logout/",
        LogoutView.as_view(next_page=reverse_lazy("UNRCE_APP:index")),
        name="logout",
    ),
    
    # Added signup view here
    path("signup/", SignUpView.as_view(), name="signup"),
      # Added upload view here, don't forget to
  #path("upload/", UploadImageView.as_view(), name="upload"),
  path('forgot_password/', views.forgot_password, name='forgot_password'),
  re_path(r'^reset_password/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', views.reset_password, name='reset_password_confirm'),
  path('contact-us/', views.contact_us, name='contact-us'),

  path('projects/', views.projects, name='projects'),   # List of (approved) projects
  path('projects/<int:project_id>/', views.project_specific, name='project_specific'),  # The page for a specific project

  path('specific_project/', views.specific_project, name='specific_project'),   # TOM'S OLD CODE, NOT USING
  path('projects/<int:project_id>/approve/', views.approve_project, name='approve_project'),    # Used to approve project
  path('projects/<int:project_id>/reject/', views.reject_project, name='reject_project'),       # Used to reject project
  path('projects/<int:project_id>/pending/', views.make_pending_project, name='make_pending_project'),       # Used to make project pending
  path('change_approval/<int:project_id>/', views.change_approval, name='change_approval'),

  path('user-search/', views.search_users, name='search_users'),
  path('delete-users/', views.delete_users, name='delete_users'),
  path('download-users/', views.download_users, name='download-users'),
  path('make-admin/', views.make_admin_view, name='make-admin'),



#   path('specific_project/<int:project_id>/', views.specific_project, name='specific_project'),
  path('new_captcha/', views.new_captcha, name='new_captcha'),
  path('projects/', views.projects, name='projects'),
  path('specific_project/', views.specific_project, name='specific_project'),
  path("create_project/", CreateProject.as_view(), name="create_project"),
  path("myaccount/", views.myaccount, name="myaccount"),
  path("myaccount_edit/", views.myaccount_edit, name="myaccount_edit"),
  path('edit_project/<int:project_id>/', views.edit_project, name='edit_project'),
  path('users/', views.users_info, name='users'),
  path('admin/fetch_projects/', views.fetch_projects, name='fetch_projects'),
  path('project-search/', views.project_search, name='project_search'),
  path('delete_projects/', views.delete_projects, name='delete_projects'), 
  path("pending_projects/", views.pending_projects, name="pending_projects"),   # Shows all pending projects

  path("rejected_projects/", views.rejected_projects, name="rejected_projects"),    # Shows all rejected projects
#   path('approve_project/', views.approve_project, name='approve_project'),
  path('activate/<str:uidb64>/<str:token>/', views.activate_account, name='activate_account'),
  path('faq/', views.faq, name='faq'),
  path('download_projects_csv/', views.download_projects_csv, name='download_projects_csv'),    # To download projects
]

UNRCE-django/UNRCE_APP/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from .models import CustomUser
from .models import Project #, Image
from .models import SDG

from django.core.exceptions import ValidationError

# We use Django's built-in ModelForm class
# class UploadImageForm(forms.ModelForm):
#   class Meta:
#     model = Image
#     # only image and title fields from the Image
#     # model will be available to user
#     fields = ["image", "title"]
#     # Let's play with it a little to
#     # get a taste of Django widgets
#     widgets = {
#       "title": forms.Textarea(
#         attrs={
#           "cols": 60,
#           "rows": 3,
#         }
#       ),
#     }

#Create a form that will use email for authentication 
class CustomAuthenticationForm(AuthenticationForm):
    username = forms.EmailField(label="Email")


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ("email",)
        labels = {
            "email": "Email",
        }

    # def clean_email(self):
    #     email = self.cleaned_data.get("email")
    #     if re.search(r'[0-9!@#$%^&*(),.?":{}|<>]', email):
    #         raise ValidationError("Name should not contain numbers or special characters.")
    #     return email


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = '__all__'


class UserSearchForm(forms.Form):
    search_query = forms.CharField(label='Search Users', max_length=100, required=False)


# Update the user's details
class UpdateAccountForm(forms.ModelForm):
    emails_enabled = forms.BooleanField(
        required=False,
        widget=forms.CheckboxInput(),
        initial=True
    )

    interested_sdgs = forms.ModelMultipleChoiceField(
        queryset=SDG.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        label="Select your SDGs of interest",
    )

    class Meta:
        model = CustomUser
        fields = ['name', 'org', 'emails_enabled', 'rce_hub2', 'role_organisation', 'interested_sdgs']

    def clean_name(self):
        name = self.cleaned_data.get('name')
        if any(char.isdigit() for char in name) or not name.isalpha():
            raise ValidationError("Name should only contain letters and should not include any numbers or special characters.")
        return name

UNRCE-django/UNRCE_APP/views.py
from django.db.models import Q
from django.contrib import messages
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth import login, get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.contrib.sites.shortcuts import get_current_site
from django.core.exceptions import PermissionDenied
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect, HttpResponse
from django.urls import reverse
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from django.views import View

from .forms import ProjectForm, CustomUserCreationForm, UpdateAccountForm #, UploadImageForm
from .models import Project, CustomUser, Project, SDG, ProjectSDG, ESD, ProjectESD, ProjectPriorityArea, PriorityArea #, Image
from .tokens import account_activation_token

from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail

from captcha.models import CaptchaStore

from datetime import datetime

import csv



User = get_user_model()

from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth import REDIRECT_FIELD_NAME


from django.views.decorators.http import require_POST

# Define a custom function to check if the user is a superuser
def is_superuser(user):
    return user.is_superuser

def is_staff(user):
    return user.is_staff

# Apply the user_passes_test decorator to your view
@user_passes_test(is_superuser, login_url='/')  # Replace '/home/' with your home page URL
def search_users(request):
    if request.method != 'GET':
        # Return an empty queryset by default
        return render(
            request, {
                'users': CustomUser.objects.none(),
                "search_query": request.GET.get('search_query', ''),
            }
        )
    
    search_query = request.GET.get('search_query', '')

    # Perform the search query based on user input
    users = CustomUser.objects.filter(
        Q(email__icontains=search_query) |
        Q(user_name__icontains=search_query) |
        Q(interested_projects__title__icontains=search_query) |
        Q(organisation__org_name__icontains=search_query) |
        Q(role_organisation__icontains=search_query) |
        Q(interested_sdgs__sdg__icontains=search_query) |
        Q(rce_hub__hub_name__icontains=search_query)
    ).distinct()

    return render(
        request, 
        'UNRCE_APP/user_search.html', 
        { 'users': users, 'search_query': search_query }
    )

@user_passes_test(is_superuser, login_url='/') 
def make_admin_view(request):
    if request.method == 'POST':
        selected_user_ids = request.POST.getlist('user_ids')
        CustomUser.objects.filter(id__in=selected_user_ids).update(is_staff=True)
    return HttpResponseRedirect('/user-search/')



def new_captcha(request):
    """Return new captcha image and key."""
    captcha_key = CaptchaStore.generate_key()
    captcha_image_url = reverse('captcha-image', kwargs={'key': captcha_key})
    return JsonResponse({'captcha_image_url': captcha_image_url, 'captcha_key': captcha_key})

class CustomLoginView(LoginView):
    
    def form_valid(self, form):
        captcha_value = self.request.POST.get('captcha_0')
        captcha_key = self.request.POST.get('captcha_1')

        # Check the captcha
        captcha_check = CaptchaStore.objects.filter(response__iexact=captcha_value, hashkey=captcha_key)
        if not captcha_check.exists():
            messages.error(self.request, "Captcha is incorrect.")
            return self.form_invalid(form)  # Changed from super().form_invalid(form)
        
        messages.success(self.request, "Logged in successfully!")
        return super().form_valid(form)

    def form_invalid(self, form):
        captcha_key = CaptchaStore.generate_key()  # Always regenerate the captcha_key
        messages.error(self.request, "Failed to log in. Please check your credentials.")
        return render(
            self.request,
            "UNRCE_APP/login.html",{
                "form": form,
                "captcha_key": captcha_key
            }
        )

    def get(self, request, *args, **kwargs):
        captcha_key = CaptchaStore.generate_key()
        return render(
            request, 
            "UNRCE_APP/login.html", {
                "captcha_key": captcha_key, 
                "form": self.get_form()
            },
        ) 

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        
        if form.is_valid():
            return self.form_valid(form)
        
        captcha_key = CaptchaStore.generate_key()
        return render(
            request,
            "UNRCE_APP/login.html",
            {
                "form": form,
                "captcha_key": captcha_key
            }
        )


class SignUpView(View):

    def get(self, request):
        captcha_key = CaptchaStore.generate_key()
        return render(
            request,
            "UNRCE_APP/signup.html",{
                "form": CustomUserCreationForm(),
                "captcha_key": captcha_key,
            },
        )

    def post(self, request):
        form = CustomUserCreationForm(request.POST)
        captcha_value = request.POST.get('captcha_0')
        captcha_key = request.POST.get('captcha_1')
        captcha_check = CaptchaStore.objects.filter(response__iexact=captcha_value, hashkey=captcha_key)

        if not captcha_check.exists():
            messages.error(request, "Captcha is incorrect.")
            captcha_key = CaptchaStore.generate_key()  # Regenerate the captcha_key
            return render(
                request,
                "UNRCE_APP/signup.html",
                {
                    "form": form,  # Use the same form instance to retain the user's input
                    "captcha_key": captcha_key,
                },
            )

        if not form.is_valid():
            messages.error(request, "Form invalid!")
            captcha_key = CaptchaStore.generate_key()  # Regenerate the captcha_key
            return render(
                request,
                "UNRCE_APP/signup.html",
                {
                    "form": form,  # Use the same form instance to retain the user's input
                    "captcha_key": captcha_key,
                },
            )

        email = form.cleaned_data.get('email')  # Get email address
        
        # No need to query the database anymore
        user = form.save(commit=False)  # Create but do not save user object
        user.is_active = False  # Make user inactive until they confirm email
        user.save()

        # Generate token and send email
        current_site = get_current_site(request)
        mail_subject = 'Activate your account.'
        message = render_to_string(
            'UNRCE_APP/account_activation_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            }
        )

        # Send the email using SendGrid
        sg = SendGridAPIClient('')  # Make sure to replace with your SendGrid API key
        email_msg = Mail(
            from_email='Rce.uwa@gmail.com',
            to_emails=email,
            subject=mail_subject,
            html_content=message)
        response = sg.send(email_msg)
        messages.success(request, 'A reset password link has been sent to your email.')

        return render(request, 'UNRCE_APP/account_activation_sent.html')


def activate_account(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = CustomUser.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, CustomUser.DoesNotExist):
        return HttpResponse('Activation link is invalid!')
    
    if not account_activation_token.check_token(user, token):
        return HttpResponse('Activation link is invalid!')
    
    user.is_active = True
    user.email_confirmed = True
    user.save()
    messages.success(request, 'Account activated successfully.')
    login(request, user)
    return redirect('UNRCE_APP:myaccount')
        

        
def forgot_password(request):
    User = get_user_model()
    if request.method != "POST":
        return render(request, 'UNRCE_APP/forgot_password.html')
    
    email = request.POST['email']
    user = User.objects.filter(email=email).first()

    if not user:
        messages.error(request, 'No account with this email address exists.')
        return render(request, 'UNRCE_APP/forgot_password.html')
    
    current_site = get_current_site(request)
    mail_subject = 'Reset your password.'
    message = render_to_string(
        'UNRCE_APP/reset_password_email.html', {
            'user': user,
            'domain': current_site.domain,
            'uid': urlsafe_base64_encode(force_bytes(user.pk)),
            'token': account_activation_token.make_token(user),
        }
    )
    
    # Send the email using SendGrid, TODO: Include the API Key in the settings file
    sg = SendGridAPIClient('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') 
    email_msg = Mail(
        from_email='Rce.uwa@gmail.com',
        to_emails=email,
        subject=mail_subject,
        html_content=message,
    )
    response = sg.send(email_msg)
    messages.success(request, 'A reset password link has been sent to your email.')
    return render(request, 'UNRCE_APP/email_sent_confirmation.html')

#display reset password page
def reset_password(request, uidb64, token):
    User = get_user_model()
    try:

UNRCE-django/UNRCE_APP/templates/UNRCE_APP/account_activation_email.html
<p>Dear {{ user.email }},</p>
<p>Thank you for registering. Please click to activate your account: <a href="http://{{ domain }}{% url 'UNRCE_APP:activate_account' uidb64=uid token=token %}">Activate Account</a></p>
<p>If you do not wish to activate your account, or didn't register, this email can be safely ignored.</p>

UNRCE-django/UNRCE_APP/templates/UNRCE_APP/account_activation_sent.html
{% extends "UNRCE_APP/base.html" %}
{% block content %}

<div class="activation-box">
    <div class="activation-title">Activation Email Sent</div>

    <p>
    Thank you for signing up! An email with the activation link has been sent to your provided email address. Please check your email and click on the link to activate your account.
    </p>

    <div class="return-home">
        <a href="{% url 'UNRCE_APP:index' %}">Return to Home</a>
    </div>
</div>

{% endblock content %}

UNRCE-django/UNRCE_APP/templates/UNRCE_APP/contact-us.html
{% extends "UNRCE_APP/base.html" %}
{% load static %}

{%block linking%}
<style>
    body {
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        background-color: #f7f9fc;
        line-height: 1.6;
    }

    .small-heading {
        text-align: center;
        padding: 5vh;
        font-size: 2em;
        color: var(--accent-bg);
        margin-bottom: 20px;
    }

    .sections {
        display: flex;
        flex-direction: row;
        justify-content: space-between;
        padding: 20px;
        max-width: 95%;
        margin: 20px auto;
    }

    .sections h2 {
        color: var(--accent-bg);
    }

    .map-section, .contact-details, .endorsement-section {
        flex: 1;
        padding: 30px;
        background-color: #ffffff;
        border-radius: 8px;
        box-shadow: 0 5px 15px rgba(0, 0, 0, 0.1);
        margin: 0 10px;
        color: black;
    }

    .map-section h2, .contact-details h2, .endorsement-section h2 {
        border-bottom: 2px solid #e4e4e4;
        padding-bottom: 10px;
        margin-bottom: 20px;
    }

    .map {
        width: 100%;
        height: 300px;
        border-radius: 8px;
        overflow: hidden;
    }

    /* ... Other styles ... */

    .endorsement-photo {
        float: left;  /* Float the image to the left */
        width: 100%;
        max-width: 150px;
        margin: 20px 20px 20px 0; /* Right margin added to create space between photo and text */
    }

    .bold-text {
        font-weight: bold; /* Making the text bolder */
    }

    .endorsement-section p {
        margin-top: 0;
    }

    /* Clear float after the endorsement section to ensure layout is not broken */
    .endorsement-section::after {
        content: "";
        display: table;
        clear: both;
    }
</style>
{%endblock linking%}


{% block content %}
<p class="small-heading">Contact Us</p>
<div class="sections">
    <div class="map-section">
        <h2>Location Map</h2>
        <div class="map">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3381.5345283784644!2d115.81656931515616!3d-31.980173781355417!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2a32badd5aca0235%3A0x504f0b535df4ee0!2sThe%20University%20of%20Western%20Australia%20(UWA),%20Perth!5e0!3m2!1sen!2sus!4v1632433029150!5m2!1sen!2sus" width="100%" height="300" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
        </div>
    </div>

    <div class="contact-details">
        <h2>Contact Details</h2>
        <p>If you have any queries, please contact us at:</p>
        <p class="bold-text">Email: rce@uwa.edu.au</p>
        <p>The secretariat address is located at:</p>
        <p class="bold-text">UWA Crawley- office of DVCE, 35 Stirling hwy Crawley</p>
    </div>
    
    <div class="endorsement-section">
        <h2>Executive Sponsor</h2>
        <img src="{% static 'images/davidsadler.jpg' %}" alt="David Sadler" class="endorsement-photo">
        <p><div class="bold-text">Professor David Sadler,</div>Deputy Vice-Chancellor (Education) at UWA, is the executive sponsor of this program. Professor Sadler has shown exemplary dedication in the field of education, making significant contributions to the universities academic excellence and reputation.</p>
    </div>
</div>

{% endblock %}

UNRCE-django/UNRCE_APP/templates/UNRCE_APP/contactus.html
{% extends "UNRCE_APP/base.html" %}

{% block content %}
<p> Here is some Contact information</p>
{% endblock content %}

UNRCE-django/UNRCE_APP/templates/UNRCE_APP/index.html
{% extends "UNRCE_APP/base.html" %}

{% load static %}

{%block linking%}
<link rel="stylesheet" type="text/css" href="{% static 'UNRCE_APP/project.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'UNRCE_APP/index.css' %}">
<style>
	.header-photo {
	    width: 120%;
        height: 170px;
        background-image: url('{% static 'images/header.webp' %}');
        background-repeat: no-repeat;
        background-position: center center;
        background-size: cover; /* This will cover the entire div without stretching */
        grid-column: 1/-1;
        border-radius: 0;
    }
</style>
{%endblock linking%}

{% block content %}
<div class="header-photo"></div>
<div class="page-wrapper">
    <div class="sidebar">
        <h2 class="sub-title">Project Highlights</h2>
        <ul class="projects-list">
            <div class="project-listing" id="projectGrid" data-baseurl="{% url 'UNRCE_APP:specific_project' %}">
            <div class="project-box">
                <a href="{% url 'UNRCE_APP:specific_project' %}">
                        <div class="project-sidebar" onclick="goToDetails(event, this.children[0].src, this.children[1].textContent)" style="cursor:pointer;">
                                <img src="http://www.thewowstyle.com/wp-content/uploads/2015/01/nature-images..jpg" alt="Project 1" class="project-image">
                                <h4 class="project-title-sidebar">Project 1</h4>
                        </div>
                </a>
            </div>
            <div class="project-box">
                <a href="{% url 'UNRCE_APP:specific_project' %}">
                        <div class="project-sidebar" onclick="goToDetails(event, this.children[0].src, this.children[1].textContent)" style="cursor:pointer;">
                                <img src="https://www.bwallpaperhd.com/wp-content/uploads/2021/01/NashPoint.jpg" alt="Project 2" class="project-image">
                                <h4 class="project-title-sidebar">Project 2</h4>
                        </div>
                </a>
            </div>
            <div class="project-box">
                <a href="{% url 'UNRCE_APP:specific_project' %}">
                        <div class="project-sidebar" onclick="goToDetails(event, this.children[0].src, this.children[1].textContent)" style="cursor:pointer;">
                                <img src="https://wallsdesk.com/wp-content/uploads/2016/05/Waterfalls-Photos.jpg" alt="Project 3" class="project-image">
                                <h4 class="project-title-sidebar">Project 3</h4>
                        </div>
                </a>
            </div>
            <div class="project-box">
                <a href="{% url 'UNRCE_APP:specific_project' %}">
                        <div class="project-sidebar" onclick="goToDetails(event, this.children[0].src, this.children[1].textContent)" style="cursor:pointer;">
                                <img src="https://wallsdesk.com/wp-content/uploads/2016/05/Waterfalls-Photos.jpg" alt="Project 3" class="project-image">
                                <h4 class="project-title-sidebar">Project 4</h4>
                        </div>
                </a>
            </div>
            <div class="project-box">
                <a href="{% url 'UNRCE_APP:specific_project' %}">
                        <div class="project-sidebar" onclick="goToDetails(event, this.children[0].src, this.children[1].textContent)" style="cursor:pointer;">
                                <img src="https://wallsdesk.com/wp-content/uploads/2016/05/Waterfalls-Photos.jpg" alt="Project 3" class="project-image">
                                <h4 class="project-title-sidebar">Project 5</h4>
                        </div>
                </a>
            </div>
            </div>
     
            <h2 class="partner-title">Our Partners</h2>
            <div class="partners-box">
                    <article class="text-content">
                            <ul class="partner-list">
                                    <li><a href="https://www.un.org/" target="_blank">United Nations</a></li>
                                    <li><a href="https://www.undp.org/" target="_blank">United Nations Development Programme (UNDP)</a></li>
                                    <li><a href="https://www.unesco.org/" target="_blank">United Nations Educational, Scientific and Cultural Organization (UNESCO)</a></li>
                                    <li><a href="https://www.uwa.edu.au/" target="_blank">The University of Western Australia (UWA)</a></li>
                                    <li><a href="https://www.wwf.org/" target="_blank">World Wildlife Fund (WWF)</a></li>
                                    <li><a href="https://www.greenpeace.org/" target="_blank">Greenpeace</a></li>
                                    <li><a href="https://www.conservation.org/" target="_blank">Conservation International</a></li>
                                    <li><a href="https://www.sierraclub.org/" target="_blank">Sierra Club</a></li>
                            </ul>
                    </article>
            </div>      
    </div>
<div class="main-div">
        <h1 class="title-box">What is UNRCE?</h1>
        <article class="info-background">
                <p class="info-text">The United Nations Regional Centre of Expertise (UNRCE) is an international initiative spearheaded by the United Nations. It aims to foster collaborative partnerships at regional levels to address the pressing challenges of sustainable development. Through education and research, RCEs promote and advance local sustainable development strategies tailored to the specific needs and challenges of their respective regions. </p>
        </article>
        <h1 class="title-box">Our History</h1>
        <article class="info-background lower">
                <p class="info-text lower">The journey of UNRCE began with the global call from the United Nations to address sustainability issues in an integrative manner. Recognizing the importance of collective efforts, the UN established the Regional Centres of Expertise as platforms to collaborate, learn, and adapt. Over the years, these centres have grown in number, strength, and impact, contributing significantly to regional sustainable development narratives and practices. </p>
        </article>
        <h1 class="title-box">What is UNRCE WA?</h1>
        <article class="info-background">
                <p class="info-text">The UNRCE for Western Australia (UNRCE WA) functions as the secretariat for the region, with UWA holding a pivotal role in its operations. UNRCE WA consists of two main hubs: Perth and the Great Southern, the latter being based at the UWA Albany Campus. As part of this dynamic network, UNRCE WA dedicates its efforts to foster partnerships, drive research, and promote educational initiatives that resonate with the unique sustainability challenges and opportunities found in Western Australia.</p>
        </article>
        
            <h1 class="title-box">Our Initiatives</h1>
            <div class="initiatives-wrapper">
            <div class="flip-container">
            <label class="flip-card">
                <input type="checkbox" class="flip-checkbox">
                    <div class="flip-card-inner">
                            <div class="flip-card-front" style="background-image: url('{% static 'images/valley.jpeg' %}');">
                                    <div class="flip-card-overlay">
                                        <span class="overlay-text">More Information</span>
                                    </div>
                                </div>
                            <div class="flip-card-back">
                                    <h2 class="initiative-h2">Initiative 1</h2>
                                    <p class="initiative-text" >Just some basic information about an initiative</p>
                                </div>
                    </div>
                </label>
            <label class="flip-card">
                <input type="checkbox" class="flip-checkbox">
                <div class="flip-card-inner">
                        <div class="flip-card-front" style="background-image: url('{% static 'images/meelup.jpeg' %}');">
                                <div class="flip-card-overlay">
                                    <span class="overlay-text">More Information</span>
                                </div>
                            </div>
                        <div class="flip-card-back">
                                <h2 class="initiative-h2">Initiative 2</h2>
                                <p class="initiative-text">Just some basic information about an initiative</p>
                        </div>
                </div>
            </label>
            <label class="flip-card">
                <input type="checkbox" class="flip-checkbox">
                <div class="flip-card-inner">
                            <div class="flip-card-front" style="background-image: url('{% static 'images/ESD_for_2030.png' %}');">
                                <div class="flip-card-overlay">
                                    <span class="overlay-text">More Information</span>
                                </div>
                            </div>
                        <div class="flip-card-back" style="background-color: white;">
                                <h2 class="initiative-h2">Initiative 3</h2>
                                <p class="initiative-text">Just some basic information about an initiative</p>
                        </div>
                </div>
            </label>
        </div>
    </div>
    </div>
    <div style="clear: both;"></div>
</div>
<script src="{% static 'UNRCE_APP/projects.js' %}"></script>
{% endblock content %}

UNRCE-django/UNRCE_APP/templates/UNRCE_APP/pending_projects.html
{% extends "UNRCE_APP/base.html" %}
{% load static %}
{% block content %}

<p class="small-heading"> Pending Projects</p>

{% if user.is_superuser %}
<a href="{% url 'UNRCE_APP:projects' %}">
    <button id="approvedProjects"> Go to Approved Projects</button>
</a>
{% endif %}
<div class="project-grid" id="projectGrid" data-baseurl="{% url 'UNRCE_APP:specific_project' %}">
    {% for project in project_query %}
    <a href="{% url 'UNRCE_APP:project_specific' project.id %}">
            <div class="project">
                <img src="/media/{{ project.project_cover_image|default:"project_images/broken_image.svg" }}" alt="Cover Image">
                <h3 class="projectTitle"> {{ project.title }} </h3>
            </div>
        </a>
    {% endfor %}
</div>

<script src="{% static 'UNRCE_APP/projects.js' %}"></script>
{% endblock content %}